// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPbOAyUIuiooj_ZNchB3cUpFiacbJ9huI',
    appId: '1:355640515279:web:e9724bb93c4bc61ad5b5ba',
    messagingSenderId: '355640515279',
    projectId: 'tumbler-store',
    authDomain: 'tumbler-store.firebaseapp.com',
    storageBucket: 'tumbler-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAke3uCRhE_R13oVqO3FDMUhHI_KFXmczk',
    appId: '1:355640515279:android:a1dc65c51c1049b9d5b5ba',
    messagingSenderId: '355640515279',
    projectId: 'tumbler-store',
    storageBucket: 'tumbler-store.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPbOAyUIuiooj_ZNchB3cUpFiacbJ9huI',
    appId: '1:355640515279:web:bcb12a53fb3279f1d5b5ba',
    messagingSenderId: '355640515279',
    projectId: 'tumbler-store',
    authDomain: 'tumbler-store.firebaseapp.com',
    storageBucket: 'tumbler-store.firebasestorage.app',
  );
}
